### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by Jo-Jo0** [freifunk-darmstadt/android-freifunkfinder#1]
When starting the app, which was provided as an .apk on google drive, it instantly crashes.

Device: Galaxy Note 4 (SM-N910F) / Android 5.1.1

**Comment by benerudolph** [comment]
The App is known to have some bugs on Samsung devices.
On my device the map / node data is not loaded.
Device: Galaxy S5 / Android 5.0
@Jo-Jo0 Can you provide a logcat of the app crashing?

**Comment by Jo-Jo0** [comment]
Found a fix for my issue: It seems that the app wants to use the camera of the phone right on startup, what I blocked on my device. When giving this permission to the app, it works

**Comment by soorajambadi** [comment]
Hi Jo-Jo,

Nice to here that you are interested in using our app and ready to fix bugs
in it. We found that node_description_table.xml in Github is not exactly
what we wrote, some changes had happened while uploading it, not sure how.
You can replace this file with the one attached along with this mail and
try again...We will update the correct one in Gitlab later.

The fix is proper as our app require permission to access many hardware
resources like camera, sensors etc and access to Internet, location (GPS,
Network).

under android-freifunkfinder
https://github.com/freifunk-darmstadt/android-freifunkfinder/app
https://github.com/freifunk-darmstadt/android-freifunkfinder/tree/master/app
/*build.gradle *you can see SDK versions used etc...
You can contact us by mail for any further clarification needed.

CCing Govind and Puneet.

Thanks,
Sooraj
